package com.acme.order.common.core;

/** 系统统一错误码。 */
public enum ErrorCode {
  ORDER_NOT_FOUND,
  ORDER_STATUS_INVALID,
  ORDER_DUPLICATE_SUBMIT,
  ORDER_ALREADY_PAID,
  ORDER_ALREADY_CANCELED,
  PRODUCT_NOT_FOUND,
  SKU_NOT_FOUND,
  SKU_OFF_SHELF,
  INVENTORY_NOT_ENOUGH,
  INVENTORY_RESERVATION_NOT_FOUND,
  INVENTORY_ALREADY_RELEASED,
  PAY_ORDER_NOT_FOUND,
  PAY_AMOUNT_MISMATCH,
  PAY_NOTIFY_DUPLICATED,
  MQ_PROCESS_FAILED,
  SYSTEM_BUSY,
  RATE_LIMITED,
  UNAUTHORIZED,
  FORBIDDEN,
  VALIDATION_FAILED
}
