{
 "title": "Enterprise Order System",
 "refresh": "10s",
 "panels": [
  {
   "title": "HTTP RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count[1m])) by (application)"
    }
   ]
  },
  {
   "title": "P95 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,sum(rate(http_server_requests_seconds_bucket[5m])) by (le,application))"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes) by (application,area)"
    }
   ]
  },
  {
   "title": "DB Pool Active",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "hikaricp_connections_active" }
   ]
  }
 ]
}