spring:
  config.activate.on-profile: sharding
  shardingsphere:
    datasource:
      names: ds0,ds1
      ds0: { type: com.zaxxer.hikari.HikariDataSource, jdbc-url: "${SHARD_DB0_URL:jdbc:mysql://localhost:3306/order_trade_0}", username: "${MYSQL_USER:order}", password: "${MYSQL_PASSWORD:order123456}" }
      ds1: { type: com.zaxxer.hikari.HikariDataSource, jdbc-url: "${SHARD_DB1_URL:jdbc:mysql://localhost:3306/order_trade_1}", username: "${MYSQL_USER:order}", password: "${MYSQL_PASSWORD:order123456}" }
    rules.sharding:
      default-database-strategy.standard: { sharding-column: user_id, sharding-algorithm-name: db-inline }
      tables.trade_order: { actual-data-nodes: "ds$->{0..1}.trade_order_$->{0..7}", table-strategy.standard: { sharding-column: id, sharding-algorithm-name: order-inline } }
      tables.trade_order_item: { actual-data-nodes: "ds$->{0..1}.trade_order_item_$->{0..7}", table-strategy.standard: { sharding-column: order_id, sharding-algorithm-name: order-item-inline } }
      binding-tables: [trade_order, trade_order_item]
      sharding-algorithms:
        db-inline: { type: INLINE, props: { algorithm-expression: "ds$->{user_id % 2}" } }
        order-inline: { type: INLINE, props: { algorithm-expression: "trade_order_$->{id % 8}" } }
        order-item-inline: { type: INLINE, props: { algorithm-expression: "trade_order_item_$->{order_id % 8}" } }
