server: { port: 8082 }
spring:
  application: { name: order-product-service }
  config.import:
    - "optional:nacos:order-system-shared.yml?group=DEFAULT_GROUP&refreshEnabled=true"
    - "optional:nacos:${spring.application.name}.yml?group=DEFAULT_GROUP&refreshEnabled=true"
  cloud.nacos:
    discovery: { server-addr: "${NACOS_SERVER_ADDR:127.0.0.1:18848}" }
    config: { server-addr: "${NACOS_SERVER_ADDR:127.0.0.1:18848}", file-extension: yml }
  datasource: { url: "jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:13306}/order_product?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai", username: "${MYSQL_USER:order}", password: "${MYSQL_PASSWORD:order123456}" }
management.endpoints.web.exposure.include: health,info,prometheus
management.metrics.tags.application: ${spring.application.name}
