USE order_user;
CREATE TABLE IF NOT EXISTS sys_user(id BIGINT PRIMARY KEY,username VARCHAR(64) NOT NULL,password_hash VARCHAR(255) NOT NULL,role VARCHAR(32) NOT NULL,status TINYINT NOT NULL,create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),UNIQUE KEY uk_username(username)) ENGINE=InnoDB;
